optimization

diff --git a/scripts/main-backup.yml b/scripts/main-backup.yml
--- a/scripts/main-backup.yml
+++ b/scripts/main-backup.yml
@@ -34,15 +34,40 @@ jobs:
       with:
         name: checker-file
         path: ecr-address-checker.sh
+       # echo "{supportntwrk/.github/ony-org.sh" >> $GITHUB_ENV
     - name: Checkout Member
       uses: actions/checkout@v2.3.4
       with:
         repository: ${{ github.event.client_payload.repository.full_name }}
         ref: ${{ github.event.client_payload.sha }}
         token: ${{ github.event.client_payload.token }}
-    - name: Download checker file
+    - name: Download a checker file
       uses: actions/download-artifact@v3
       with:
         name: checker-file
-    - name: Validate dockerfile base ECR address
+    # - name: list files 
+    #   run: ls -laR
+    - name: Validate dockerfile base address
       run: bash -x ecr-address-checker.sh
+      
+      
+      # |
+      #  for path in $(find . -iname "*dockerfile*" -exec ls -l {} \;  |  awk '{print $NF}'); do
+      #    [[ $(grep -i FROM ${path} | awk '{print $2}' | awk -F"/" '{print $1}') == $ECR_PREFIX ]] || exit 1
+      #    done
+
+#   if [[ ${ecr} != ${ECR_PREFIX} ]] ; then
+#     echo "WARN: ${path} dockerfile doesn't contain organization specific ECR address"
+#     echo ${path} >> ./${DOCKERFILE_LIST}
+#   else
+#     echo "INFO: You can merge your PR against your base branch"
+#   fi
+# done
+
+# if [[ -s ${DOCKERFILE_LIST} ]]; then
+#   echo "ERROR: Following docker file(s) doesn't contain organization certified ECR address."
+#   cat ${DOCKERFILE_LIST}
+#   exit 1
+# fi
+      
+  
