testing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -5,7 +5,9 @@ on:
       
   repository_dispatch:
     types: [org-workflow-bot]  
-   
+env:
+  ECR_PREFIX: "498031324058.dkr.ecr.us-east-1.amazonaws.com"
+
 jobs:
   register:
     runs-on: ubuntu-latest
@@ -19,21 +21,36 @@ jobs:
         name: ${{ github.workflow }}
         enforce: true
         documentation: "ony-org.sh"
-    - name: list files
-      run: ls -laR; pwd 
-  # main:
-  #   needs: [register]
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #   - name: Checkout Self
-  #     uses: actions/checkout@v2.3.4
-  #   - name: Checkout Member
-  #     uses: actions/checkout@v2.3.4
-  #     with:
-  #       repository: ${{ github.event.client_payload.repository.full_name }}
-  #       ref: ${{ github.event.client_payload.sha }}
-  #       token: ${{ github.event.client_payload.token }}
-  #   - name: checking env 
-  #     run: ls -laR /home/runner/work/
-  #   - name: Validate dockerfile base address
-  #     run: bash -x ony-org.sh   
+
+  main:
+    needs: [register]
+    runs-on: ubuntu-latest
+    steps:
+    - name: Checkout Self
+      uses: actions/checkout@v2.3.4
+    - name: Checkout Member
+      uses: actions/checkout@v2.3.4
+      with:
+        repository: ${{ github.event.client_payload.repository.full_name }}
+        ref: ${{ github.event.client_payload.sha }}
+        token: ${{ github.event.client_payload.token }}
+    - name: Validate dockerfile base address
+      run: |
+       for path in $(find . -iname "*dockerfile*" -exec ls -l {} \;  |  awk '{print $NF}'); do
+         [[ $(grep -i FROM ${path} | awk '{print $2}' | awk -F"/" '{print $1}') == $ECR_PREFIX ]] || exit 1
+
+#   if [[ ${ecr} != ${ECR_PREFIX} ]] ; then
+#     echo "WARN: ${path} dockerfile doesn't contain organization specific ECR address"
+#     echo ${path} >> ./${DOCKERFILE_LIST}
+#   else
+#     echo "INFO: You can merge your PR against your base branch"
+#   fi
+# done
+
+# if [[ -s ${DOCKERFILE_LIST} ]]; then
+#   echo "ERROR: Following docker file(s) doesn't contain organization certified ECR address."
+#   cat ${DOCKERFILE_LIST}
+#   exit 1
+# fi
+      
+  
